/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t -o src/components/Three/Models/Giraffe.tsx garbage/models/Giraffe.glb
Giraffe by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/c3mlL5owLJA)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCube5_1: THREE.Mesh
    pCube5_1_1: THREE.Mesh
  }
  materials: {
    blinn1SG: THREE.MeshStandardMaterial
    blinn2SG: THREE.MeshStandardMaterial
  }
}

export function Giraffe(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Giraffe-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube5_1.geometry} material={materials.blinn1SG} />
      <mesh geometry={nodes.pCube5_1_1.geometry} material={materials.blinn2SG} />
    </group>
  )
}

useGLTF.preload('/Giraffe-transformed.glb')
