/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t -o src/components/Three/Models/HomeIsland.tsx garbage/models/HomeIsland.glb
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { degreesToRadians } from '../util/util'
import { useControls } from 'leva'

type GLTFResult = GLTF & {
  nodes: {
    Island: THREE.Mesh
  }
  materials: {
    Mat: THREE.MeshStandardMaterial
  }
}

export function HomeIsland(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/HomeIsland-transformed.glb') as GLTFResult
  // const { rot, x, z } = useControls("HomeIsland", { rot: { step: 1, value: 30, }, x: { step: 0.01, value: 0.55, }, z: { step: 0.01, value: -0.3, }, })
  return (
    <group {...props} dispose={null} scale={0.06} rotation={degreesToRadians([0, 26, 0])} position={[0.53, -0.09, -0.47]} castShadow>
      <mesh geometry={nodes.Island.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/HomeIsland-transformed.glb')
