/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t -o src/components/Three/Models/Pipes.tsx garbage/models/Pipes.glb
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Pipes_1: THREE.Mesh
    Pipes_2: THREE.Mesh
  }
  materials: {
    Grey: THREE.MeshStandardMaterial
    Grey2: THREE.MeshStandardMaterial
  }
}

export function Pipes(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Pipes-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, -Math.PI / 2]} scale={88.009}>
        <mesh geometry={nodes.Pipes_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Pipes_2.geometry} material={materials.Grey2} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pipes-transformed.glb')
