/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t -o src/components/Three/Models/Robot.tsx garbage/models/Robot.glb
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    group346538596: THREE.Mesh
    group140126695: THREE.Mesh
    group1093835587: THREE.Mesh
    group572601098: THREE.Mesh
    group977054201: THREE.Mesh
    group221446973: THREE.Mesh
    mesh1540490610: THREE.Mesh
    mesh1540490610_1: THREE.Mesh
    mesh1540490610_2: THREE.Mesh
    group1042300199: THREE.Mesh
    group79361964: THREE.Mesh
  }
  materials: {
    mat16: THREE.MeshStandardMaterial
    mat13: THREE.MeshStandardMaterial
    mat17: THREE.MeshStandardMaterial
    mat21: THREE.MeshStandardMaterial
    mat23: THREE.MeshStandardMaterial
    mat20: THREE.MeshStandardMaterial
    mat11: THREE.MeshStandardMaterial
    mat12: THREE.MeshStandardMaterial
    mat14: THREE.MeshStandardMaterial
    mat8: THREE.MeshStandardMaterial
    mat5: THREE.MeshStandardMaterial
  }
}

export function Robot(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Robot-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group346538596.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group140126695.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1093835587.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group572601098.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group977054201.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group221446973.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1042300199.geometry} material={materials.mat8} />
      <mesh geometry={nodes.group79361964.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1540490610.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh1540490610_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1540490610_2.geometry} material={materials.mat14} />
    </group>
  )
}

useGLTF.preload('/Robot-transformed.glb')
