/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t -o src/components/Three/Models/TokyoTower.tsx garbage/models/TokyoTower.glb
東京タワー by Kenta Imai [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/frPqTFGeRNM)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    tokyo_tower_town_working: THREE.Mesh
  }
  materials: {
    ['palette.002']: THREE.MeshStandardMaterial
  }
}

export function TokyoTower(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/TokyoTower-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tokyo_tower_town_working.geometry} material={materials['palette.002']} />
    </group>
  )
}

useGLTF.preload('/TokyoTower-transformed.glb')
