/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t -o src/components/Three/Models/Torii.tsx garbage/models/Torii.glb
Japanese Torii by Jacques Fourie [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/cXyQGUwmlA5)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    group1663585988: THREE.Mesh
    group1978873540: THREE.Mesh
    group608985182: THREE.Mesh
    group1562799948: THREE.Mesh
    mesh1119409316: THREE.Mesh
    mesh1119409316_1: THREE.Mesh
    mesh1119409316_2: THREE.Mesh
  }
  materials: {
    mat14: THREE.MeshStandardMaterial
    mat20: THREE.MeshStandardMaterial
    mat16: THREE.MeshStandardMaterial
    mat11: THREE.MeshStandardMaterial
    mat12: THREE.MeshStandardMaterial
    mat8: THREE.MeshStandardMaterial
    mat23: THREE.MeshStandardMaterial
  }
}

export function Torii(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Torii-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1663585988.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1978873540.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group608985182.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1562799948.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh1119409316.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1119409316_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1119409316_2.geometry} material={materials.mat23} />
    </group>
  )
}

useGLTF.preload('/Torii-transformed.glb')
