/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -T -t -o src/components/Three/Models/TreeStump.tsx garbage/models/TreeStump.glb
This work is based on "Polygon Tree Pack" (https://sketchfab.com/3d-models/polygon-tree-pack-36dacc2aeacb4f9f94385f63b978c3ca) by StreakByte (https://sketchfab.com/StreakByte) licensed under CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_651: THREE.Mesh
  }
  materials: {
    brown: THREE.MeshStandardMaterial
  }
}

export function TreeStump(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/TreeStump-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_651.geometry} material={materials.brown} scale={0.171} />
    </group>
  )
}

useGLTF.preload('/TreeStump-transformed.glb')
