import { type NextPage } from "next";
import Head from "next/head";
import GameCanvas from "../components/Three/GameCanvas";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-800 to-[#15162c]">
        <GameCanvas />
      </main>
    </>
  );
};

export default Home;

