
import { ContentGenre } from "@prisma/client"
export const genreIds = [
    "action",
    "adventure",
    "fighting",
    "music",
    "platform",
    "puzzle",
    "quiz_trivia",
    "racing",
    "rpg",
    "shooter",
    "simulator",
    "slasher",
    "sport",
    "strategy",
    "turn_based",
    "cars",
    "comedy",
    "drama",
    "ecchi",
    "fantasy",
    "game",
    "harem",
    "historical",
    "horror",
    "kids",
    "magic",
    "mecha",
    "military",
    "mystery",
    "parody",
    "police",
    "psychological",
    "romance",
    "school",
    "sci_fi",
    "slice_of_life",
    "space",
    "sports",
    "super_power",
    "supernatural",
    "thriller",
    "vampire",
    "yaoi",
    "yuri",
    "crime",
    "documentary",
    "family",
    "history",
    "war",
    "western",
] as const
export type GenreId = typeof genreIds[number]
export const genreIdToName = new Map<ContentGenre,string>([
    ["action", "Action"],
    ["adventure", "Adventure"],
    ["fighting", "Fighting"],
    ["music", "Music"],
    ["platform", "Platform"],
    ["puzzle", "Puzzle"],
    ["quiz_trivia", "Quiz/Trivia"],
    ["racing", "Racing"],
    ["rpg", "RPG"],
    ["shooter", "Shooter"],
    ["simulator", "Simulator"],
    ["slasher", "Slasher"],
    ["sport", "Sport"],
    ["strategy", "Strategy"],
    ["turn_based", "Turn-based"],
    ["cars", "Cars"],
    ["comedy", "Comedy"],
    ["drama", "Drama"],
    ["ecchi", "Ecchi"],
    ["fantasy", "Fantasy"],
    ["game", "Game"],
    ["harem", "Harem"],
    ["historical", "Historical"],
    ["horror", "Horror"],
    ["kids", "Kids"],
    ["magic", "Magic"],
    ["mecha", "Mecha"],
    ["military", "Military"],
    ["mystery", "Mystery"],
    ["parody", "Parody"],
    ["police", "Police"],
    ["psychological", "Psychological"],
    ["romance", "Romance"],
    ["school", "School"],
    ["sci_fi", "Sci-Fi"],
    ["slice_of_life", "Slice of Life"],
    ["space", "Space"],
    ["sports", "Sports"],
    ["super_power", "Super Power"],
    ["supernatural", "Supernatural"],
    ["thriller", "Thriller"],
    ["vampire", "Vampire"],
    ["yaoi", "Yaoi"],
    ["yuri", "Yuri"],
    ["crime", "Crime"],
    ["documentary", "Documentary"],
    ["family", "Family"],
    ["history", "History"],
    ["war", "War"],
    ["western", "Western"],
])
export const genreNameToId = new Map<string,ContentGenre>([
    ["Action", "action"],
    ["Adventure", "adventure"],
    ["Fighting", "fighting"],
    ["Music", "music"],
    ["Platform", "platform"],
    ["Puzzle", "puzzle"],
    ["Quiz/Trivia", "quiz_trivia"],
    ["Racing", "racing"],
    ["RPG", "rpg"],
    ["Shooter", "shooter"],
    ["Simulator", "simulator"],
    ["Slasher", "slasher"],
    ["Sport", "sport"],
    ["Strategy", "strategy"],
    ["Turn-based", "turn_based"],
    ["Cars", "cars"],
    ["Comedy", "comedy"],
    ["Drama", "drama"],
    ["Ecchi", "ecchi"],
    ["Fantasy", "fantasy"],
    ["Game", "game"],
    ["Harem", "harem"],
    ["Historical", "historical"],
    ["Horror", "horror"],
    ["Kids", "kids"],
    ["Magic", "magic"],
    ["Mecha", "mecha"],
    ["Military", "military"],
    ["Mystery", "mystery"],
    ["Parody", "parody"],
    ["Police", "police"],
    ["Psychological", "psychological"],
    ["Romance", "romance"],
    ["School", "school"],
    ["Sci-Fi", "sci_fi"],
    ["Slice of Life", "slice_of_life"],
    ["Space", "space"],
    ["Sports", "sports"],
    ["Super Power", "super_power"],
    ["Supernatural", "supernatural"],
    ["Thriller", "thriller"],
    ["Vampire", "vampire"],
    ["Yaoi", "yaoi"],
    ["Yuri", "yuri"],
    ["Crime", "crime"],
    ["Documentary", "documentary"],
    ["Family", "family"],
    ["History", "history"],
    ["War", "war"],
    ["Western", "western"],
])    
